name: Build and Deploy to AWS

on:
  push:
    branches:
      - master # Körde workflow när du pushar till master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorygit
        uses: actions/checkout@v4

      - name: Set up Java JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build with Maven
        run: mvn clean install