name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload to S3
        run: |
          aws s3 cp target/todolist-0.0.1-SNAPSHOT.jar s3://minspringapp-deploy-bucket/minspringapp.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Create Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version --application-name Todo --version-label ${{ github.sha }} --source-bundle S3Bucket=minspringapp-deploy-bucket,S3Key=minspringapp.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Update Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment --environment-name minspringapp-env --version-label ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
